#pragma once

#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <string>

namespace ashgrove {

// TinyMLP: hand-coded fixed-size MLP with ReLU hidden + sigmoid output.
// No external dependencies (no PyTorch, no Eigen). Deterministic forward pass.
// Used for: attention gating, action evaluation, world-model prediction.
// Architecture: N_in -> N_hidden -> N_out (single hidden layer).
//
// Weights are stored as plain float arrays; can be loaded from JSON files
// generated by tools/train_compact_mlp.py.
//
// Training (offline, done once) uses synthetic data generated by NIM or
// tools/gen_dataset.py --cognitive_mlp mode. Online adaptation uses the
// bounded update methods (update_world_model_bias, etc.) on a small
// bias vector, NOT the weights themselves.

template <std::size_t N_IN, std::size_t N_HIDDEN, std::size_t N_OUT>
class TinyMLP {
 public:
  static constexpr std::size_t kW1Size = N_HIDDEN * N_IN;
  static constexpr std::size_t kB1Size = N_HIDDEN;
  static constexpr std::size_t kW2Size = N_OUT * N_HIDDEN;
  static constexpr std::size_t kB2Size = N_OUT;

  TinyMLP() { zero_init(); }

  void zero_init() {
    std::memset(W1_.data(), 0, sizeof(W1_));
    std::memset(b1_.data(), 0, sizeof(b1_));
    std::memset(W2_.data(), 0, sizeof(W2_));
    std::memset(b2_.data(), 0, sizeof(b2_));
  }

  // Forward pass. `inputs` must have N_IN floats; outputs goes into `out`
  // (must have N_OUT floats). Hidden activations are stored in `hidden_buf`
  // if non-null (caller-provided, N_HIDDEN floats).
  void forward(const float* inputs, float* out,
               float* hidden_buf = nullptr) const {
    float local_hidden[N_HIDDEN];
    float* h = hidden_buf ? hidden_buf : local_hidden;
    for (std::size_t i = 0; i < N_HIDDEN; ++i) {
      float acc = b1_[i];
      for (std::size_t j = 0; j < N_IN; ++j) {
        acc += W1_[i * N_IN + j] * inputs[j];
      }
      h[i] = acc > 0.0f ? acc : 0.0f;  // ReLU
    }
    for (std::size_t i = 0; i < N_OUT; ++i) {
      float acc = b2_[i];
      for (std::size_t j = 0; j < N_HIDDEN; ++j) {
        acc += W2_[i * N_HIDDEN + j] * h[j];
      }
      out[i] = 1.0f / (1.0f + std::exp(-acc));  // sigmoid
    }
  }

  // Load weights from a JSON object with keys "W1","b1","W2","b2".
  // Expected format: arrays of floats of the right size.
  // Returns true on success.
  bool load_from_json(const std::string& path) {
    std::ifstream f(path);
    if (!f) return false;
    std::string s((std::istreambuf_iterator<char>(f)),
                  std::istreambuf_iterator<char>());
    // Naive JSON array parser (we control the producer so it's safe).
    auto parse_array = [&](const std::string& key, float* dst, std::size_t n) {
      auto k = s.find("\"" + key + "\"");
      if (k == std::string::npos) return false;
      auto lb = s.find('[', k);
      auto rb = s.find(']', lb);
      if (lb == std::string::npos || rb == std::string::npos) return false;
      std::size_t i = 0;
      std::size_t pos = lb + 1;
      while (pos < rb && i < n) {
        while (pos < rb && (s[pos] == ' ' || s[pos] == ',' ||
                            s[pos] == '\n' || s[pos] == '\r' || s[pos] == '\t'))
          ++pos;
        if (pos >= rb) break;
        float v = std::stof(s.substr(pos, 32));
        dst[i++] = v;
        while (pos < rb && s[pos] != ',' && s[pos] != ']') ++pos;
      }
      return i == n;
    };
    return parse_array("W1", W1_.data(), kW1Size) &&
           parse_array("b1", b1_.data(), kB1Size) &&
           parse_array("W2", W2_.data(), kW2Size) &&
           parse_array("b2", b2_.data(), kB2Size);
  }

  const std::array<float, kW1Size>& W1() const { return W1_; }
  const std::array<float, kB1Size>& b1() const { return b1_; }
  const std::array<float, kW2Size>& W2() const { return W2_; }
  const std::array<float, kB2Size>& b2() const { return b2_; }

 private:
  std::array<float, kW1Size> W1_{};
  std::array<float, kB1Size> b1_{};
  std::array<float, kW2Size> W2_{};
  std::array<float, kB2Size> b2_{};
};

}  // namespace ashgrove
